// <auto-generated />
using BarberAPI.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarberAPI.Migrations
{
    [DbContext(typeof(BarberContext))]
    [Migration("20220924181150_BoookingTableAdded")]
    partial class BoookingTableAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarberAppDLL.Models.DomainModel.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelGUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            CreatedDateTime = "0001/01/01 00:00:00",
                            CreatorId = "C1111",
                            IsDeleted = 0,
                            Lat = "1000",
                            MainStreet = "Street10",
                            ModelGUID = "A1111",
                            Number = "3",
                            PostCode = "1111",
                            Street = "Street1",
                            Suburb = "Sub1",
                            lon = "1111"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USB",
                            CreatedDateTime = "0001/01/01 00:00:00",
                            CreatorId = "C2222",
                            IsDeleted = 0,
                            Lat = "2000",
                            MainStreet = "Street20",
                            ModelGUID = "A2222",
                            Number = "6",
                            PostCode = "2222",
                            Street = "Sreet2",
                            Suburb = "Sub2",
                            lon = "2222"
                        });
                });

            modelBuilder.Entity("BarberAppDLL.Models.DomainModel.Barber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressGuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AverageRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarberEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("ModelGUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressGuid = "A1111",
                            AverageRating = "10",
                            BarberEmail = "barber1@gmail.com",
                            BarberName = "Barber1",
                            CreatedDateTime = "0001/01/01 00:00:00",
                            CreatorId = "C1111",
                            IsDeleted = 0,
                            ModelGUID = "B1111",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AddressGuid = "A2222",
                            AverageRating = "1",
                            BarberEmail = "barber2@gmail.com",
                            BarberName = "Barber2",
                            CreatedDateTime = "0001/01/01 00:00:00",
                            CreatorId = "C2222",
                            IsDeleted = 0,
                            ModelGUID = "B2222",
                            Status = 0
                        });
                });

            modelBuilder.Entity("BarberAppDLL.Models.DomainModel.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArriveTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarberGuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("ModelGUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserGuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BarberAppDLL.Models.DomainModel.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("ModelGUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedDateTime = "0001/01/01 00:00:00",
                            CreatedDateTime = "0001/01/01 00:00:00",
                            CreatorId = "C1111",
                            CustomerAddress = "A1111",
                            CustomerEmail = "Customer1@gmail.com",
                            CustomerName = "Customer1",
                            Email = "Customer1@gmail.com",
                            IsDeleted = 0,
                            ModelGUID = "C1111",
                            UserId = "1",
                            UserName = "Customer1"
                        },
                        new
                        {
                            Id = 2,
                            CompletedDateTime = "0001/01/01 00:00:00",
                            CreatedDateTime = "0001/01/01 00:00:00",
                            CreatorId = "C2222",
                            CustomerAddress = "A2222",
                            CustomerEmail = "Customer2@gmail.com",
                            CustomerName = "Customer2",
                            Email = "Customer2@gmail.com",
                            IsDeleted = 0,
                            ModelGUID = "C2222",
                            UserId = "2",
                            UserName = "Customer2"
                        });
                });

            modelBuilder.Entity("BarberAppDLL.Models.DomainModel.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("BarberGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("ModelGUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("BarberAppDLL.Models.DomainModel.LogVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArriveTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarberGuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("ModelGUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserGuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogVisits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArriveTime = "0001/01/01 00:00:00",
                            BarberGuid = "B1111",
                            BookingTime = "0001/01/01 00:00:00",
                            CompletedDateTime = "0001/01/01 00:00:00",
                            CompletionTime = "0001/01/01 00:00:00",
                            CreatedDateTime = "0001/01/01 00:00:00",
                            CreatorId = "C1111",
                            Description = "Booking",
                            IsDeleted = 0,
                            ModelGUID = "V1111",
                            Rating = 2,
                            Reason = "Hair Cut",
                            UserGuid = "C1111"
                        },
                        new
                        {
                            Id = 2,
                            ArriveTime = "0001/01/01 00:00:00",
                            BarberGuid = "B2222",
                            BookingTime = "0001/01/01 00:00:00",
                            CompletedDateTime = "0001/01/01 00:00:00",
                            CompletionTime = "0001/01/01 00:00:00",
                            CreatedDateTime = "0001/01/01 00:00:00",
                            CreatorId = "C2222",
                            Description = "Walk In",
                            IsDeleted = 0,
                            ModelGUID = "V2222",
                            Rating = 2,
                            Reason = "Booking ",
                            UserGuid = "C2222"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
